// studio/src/pages/Privacy/Privacy.jsx
import { useState } from 'react'
import './Privacy.css'

// ── Icons ─────────────────────────────────────────────────────────
const ShieldIco = () => <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
const ChevIco   = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><polyline points="6 9 12 15 18 9"/></svg>
const CheckIco  = () => <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"><polyline points="20 6 9 17 4 12"/></svg>

const DATA_TYPES = [
  { icon: '👤', title: 'Account Info',    desc: 'Name, email, profile picture, and preferences you provide when signing up.' },
  { icon: '▶',  title: 'Watch History',  desc: 'Videos you watch and how long — used for personalised recommendations only.' },
  { icon: '🔍', title: 'Search Queries', desc: 'What you search for on AURA. Never shared with third parties.' },
  { icon: '📍', title: 'Location',       desc: 'Country-level only, inferred from IP for content availability. Not sold.' },
  { icon: '📊', title: 'Usage Analytics',desc: 'How you interact with the platform — to improve features and fix bugs.' },
  { icon: '💳', title: 'Payment Info',   desc: 'Processed via Razorpay. AURA never stores your full card number.' },
]

const RIGHTS = [
  ['Access',      'Request a copy of all data we hold about you.'],
  ['Correction',  'Ask us to fix inaccurate or incomplete data.'],
  ['Deletion',    'Request deletion of your account and all associated data.'],
  ['Portability', 'Export your data in a machine-readable format.'],
  ['Objection',   'Opt out of certain types of data processing.'],
  ['Restriction', 'Limit how we process your data in specific circumstances.'],
]

const SECTIONS = [
  {
    title: '1. Information We Collect',
    body: 'We collect information you provide directly (account registration, profile updates), information generated by your use of AURA (watch history, interactions, search queries), and technical information (IP address, device type, browser). We do not collect sensitive personal information beyond what is necessary to operate the platform.',
  },
  {
    title: '2. How We Use Your Data',
    body: 'We use your data to personalise your experience, recommend content, process payments, send relevant notifications, improve platform features, and comply with legal obligations. We never use your data for advertising on behalf of third parties. AURA products are ad-free.',
  },
  {
    title: '3. Data Sharing',
    body: 'We do not sell your personal data. We share limited data only with: service providers who help us operate the platform (cloud storage, payment processors), legal authorities when required by law, and with your explicit consent for any other purpose.',
  },
  {
    title: '4. Data Retention',
    body: 'We retain your account data for as long as your account is active. Watch history and interaction data is retained for 24 months for recommendation purposes. After account deletion, anonymised aggregate data may be retained indefinitely for analytics.',
  },
  {
    title: '5. Security',
    body: 'We use industry-standard encryption (TLS) for all data in transit. Passwords are hashed using bcrypt. We conduct regular security audits and follow responsible disclosure practices. In the event of a breach, we will notify affected users within 72 hours.',
  },
  {
    title: '6. Cookies & Tracking',
    body: 'We use strictly necessary cookies for authentication and session management. We do not use tracking or advertising cookies. Analytics are performed using anonymised, first-party data only.',
  },
  {
    title: '7. Changes to This Policy',
    body: 'We may update this Privacy Policy from time to time. We will notify you of significant changes via email and an in-app notification at least 14 days before they take effect. Your continued use of AURA after changes constitutes acceptance.',
  },
]

function Accordion({ items }) {
  const [open, setOpen] = useState(null)
  return (
    <div className="pv-accordion">
      {items.map((item, i) => (
        <div key={i} className={`pv-acc-item${open === i ? ' open' : ''}`}>
          <button className="pv-acc-btn" onClick={() => setOpen(open === i ? null : i)}>
            {item.title}
            <span className={`pv-acc-chev${open === i ? ' open' : ''}`}><ChevIco /></span>
          </button>
          {open === i && <div className="pv-acc-body">{item.body}</div>}
        </div>
      ))}
    </div>
  )
}

export default function Privacy() {
  return (
    <div className="pv-page">

      {/* ── Header ── */}
      <div className="pv-header">
        <div className="pv-header-icon"><ShieldIco /></div>
        <div>
          <p className="pv-eyebrow">Legal</p>
          <h1 className="pv-title">Privacy Policy</h1>
          <p className="pv-sub">
            We don't sell your data. We never have. Here's exactly what we collect and why.
          </p>
          <p className="pv-date">Last updated: March 2026</p>
        </div>
      </div>

      {/* ── What we collect ── */}
      <section className="pv-section">
        <h2 className="pv-section-title">What we collect</h2>
        <div className="pv-data-grid">
          {DATA_TYPES.map(d => (
            <div key={d.title} className="pv-data-card">
              <span className="pv-data-emoji">{d.icon}</span>
              <div>
                <p className="pv-data-title">{d.title}</p>
                <p className="pv-data-desc">{d.desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Full policy accordion ── */}
      <section className="pv-section">
        <h2 className="pv-section-title">Full policy</h2>
        <Accordion items={SECTIONS} />
      </section>

      {/* ── Your rights ── */}
      <section className="pv-section">
        <h2 className="pv-section-title">Your rights</h2>
        <div className="pv-rights-grid">
          {RIGHTS.map(([name, desc]) => (
            <div key={name} className="pv-right-item">
              <span className="pv-right-check"><CheckIco /></span>
              <div>
                <p className="pv-right-name">{name}</p>
                <p className="pv-right-desc">{desc}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Contact ── */}
      <section className="pv-section">
        <div className="pv-contact">
          <p className="pv-contact-title">Questions about your data?</p>
          <p className="pv-contact-desc">
            Email us at <a href="mailto:dev.muktpatel@gmail.com">dev.muktpatel@gmail.com</a> and we'll
            respond within 30 days.
          </p>
        </div>
      </section>

    </div>
  )
}